spring:
  profiles:
    active: dev
  application:
    name: llm-service
  config:
    import: configserver:${CONFIG_URI:http://localhost:8888}
  cloud:
    config:
      profile: dev
      label: main

gemini:
  api:
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent
    key: ${GEMINI_API_KEY}
