apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  labels:
    app: llm-service
    version: {{ .Chart.AppVersion | default "1.0" }}
data:
  applicaation.yml: |
    server:
      port: {{ .Values.config.server.port | default 8080 }}
    spring:
      application:
        name: {{ .Values.config.app.name | default "llm-service" }}
    gemini:
      api:
        url: {{ .Values.config.gemini.api.url |
                  default "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent" }}
        key: ${GEMINI_API_KEY}
    management:
      endpoints:
        web:
          exposure:
            include: "*"